config/routes.rb
Rails.application.routes.draw do
  resources :direct_messages, except: [:update, :edit]

  get 'public/index'

  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'home/about_us'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tweets
  resource :home, only: [:show]
  namespace :api, path: '', default: { format: 'json' } do
    namespace :v1 do
      resources :relationships
    end
  end

  root to: 'home#show'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :user, :text, presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @sent_tweets = Tweet.where(deliver: true).page(params[:page_for_sent])
    @not_sent_tweets = Tweet.where.not(deliver: true).page(params[:page_for_not_sent])
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    Tweet.find(params[:id]).update_attribute(:deliver, !true)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    respond_to do |format|
      if @tweet.save
        TweetWorker.perform_async(Rails.env.test? ? 1 : current_user.id, @tweet.id)
        # WebsocketRails[:tweets].trigger 'deliver', { text: 'dsdsds' }
        format.html { redirect_to @tweet, notice: 'Твит был успешно создан и скоро будет виден в сети.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:text)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<div class="form-group tw-form">
  <%= form_for(@tweet) do |f| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% @tweet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1>Че нового?</h1>
    <div class="field">
      <%= f.label :text, 'Ваш твит' %><br>
      <%= f.text_area :text, maxlength: 11520, id: 'input-tweet', rows: 9, class: 'form-control' %>
    </div>
    <div class="group-inline">
      <p>Кол-во символов: <span id="input-tweet-number-of-symbols">0</span></p>

      <div class="actions">
        <%= f.submit 'Создать твит', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>
<%#<div id="editable_div" contentEditable="true" onclick="this.contentEditable='true';" >TEXT BEGIN:</div>%>
<div class="progress">
  <div id="pro1" class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="43" aria-valuemin = "0" aria-valuemax="100" style="width: 5%">
    <span class="sr-only">45% Complete</span>
  </div>
</div>

app/views/tweets/_not_sent_tweets.html.erb
<table id="not-sent-tweets-table" class="table table-striped">
  <caption>Мои твиты</caption>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @not_sent_tweets.each do |tweet| %>
      <% cache tweet do %>
        <tr>
          <td><%= truncate(tweet.text, length: 33) %></td>
          <td><%= tweet.deliver %></td>
          <td><%= link_to 'Show', tweet %></td>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<%= paginate @not_sent_tweets, param_name: 'page_for_not_sent' %>

app/views/tweets/_sent_tweets.html.erb
<table class="table table-striped" id="sent-tweets-table">
  <caption>Мои твиты</caption>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sent_tweets.each do |tweet| %>
      <% cache tweet do %>
        <tr>
          <td><%= truncate(tweet.text, length: 33) %></td>
          <td><%= tweet.deliver %></td>
          <td><%= link_to 'Show', tweet %></td>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<%= paginate @sent_tweets, param_name: 'page_for_sent' %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="tweets-first-sec">
  <%= render 'sent_tweets' %>
</div>

<div class="tweets-second-sec">
  <%= render 'not_sent_tweets' %>
</div>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="tweet-display">
  <p id="notice"><%= notice %></p>
  <% if @tweet.deliver %>
    <p>Твит был опубликован в сети от вашего имени!</p>
  <% else %>
    <p>Задача для отправки твита в обработке!</p>
  <% end %>
  <p class="p__tweet-text">
    <%= @tweet.text %>
  </p>

  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path %>
</div>