config/routes.rb
Rails.application.routes.draw do
  resources :direct_messages, except: [:update, :edit]

  get 'public/index'

  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'home/about_us'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tweets
  resource :home, only: [:show]
  namespace :api, path: '', default: { format: 'json' } do
    namespace :v1 do
      resources :relationships
    end
  end

  root to: 'home#show'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="footer__trademark">&copy;
    <% start_year = 2014 %>
    <% if start_year == Time.now.year %>
        <%= start_year %>
    <% else %>
        <%= "#{start_year}-#{Time.now.year}" %>
    <% end %>
    "Twitter service"
  </p>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span>class="icon-bar"</span>
        <span>class="icon-bar"</span>
        <span>class="icon-bar"</span>
      </button>
      <li><%= link_to 'Главная', root_path, class: 'navbar-brand' %></li>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/user_info' %>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !current_user.nil? %>
  <li><%= link_to 'Выйти', signout_path %></li>
  <li><%= link_to 'Создать твит', new_tweet_path %></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Твиты <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Создать личное сообщение', new_direct_message_path %></li>
      <li><%= link_to 'Обновить статус', new_tweet_path %></li>
      <li><%= link_to 'Все твиты', tweets_path %></li>
      <li><%= link_to 'Настройки твиттера', '#' %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Войти', '/auth/twitter' %></li>
<% end %>
<li><a href="#"><%= t('hello') %></a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    Контакты <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Обратная связь', home_about_us_path %></li>
    <li><%= link_to 'Описание', home_show_path %></li>
  </ul>
</li>

app/views/layouts/_user_info.html.erb
<li>
  <div class="user-badge">

    <a href="#"><%= image_tag current_user.profile_image, class: 'navbar__img' %></a>
    <span class="nav__user_right"><%= current_user.name %></span>
  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Twitter service" %>">
    <title><%= content_for?(:title) ? yield(:title) : "Twitter service" %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'token-input-facebook', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>